# Generated by Django 6.0.3 on 2026-03-28 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OFFER_RECEIVED', 'Yangi taklif keldi'), ('OFFER_ACCEPTED', 'Taklif qabul qilindi'), ('OFFER_REJECTED', 'Taklif rad etildi'), ('DEADLINE_SOON', 'Muddat yaqinlashmoqda'), ('DEADLINE_PASSED', "Muddat o'tdi"), ('ORDER_COMPLETED', 'Ish tugatildi'), ('MESSAGE', 'Yangi xabar')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
