# Generated by Django 6.0.3 on 2026-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OFFER_RECEIVED', 'Yangi taklif keldi'), ('OFFER_ACCEPTED', 'Taklif qabul qilindi'), ('OFFER_REJECTED', 'Taklif rad etildi'), ('DEADLINE_SOON', 'Muddat yaqinlashmoqda'), ('DEADLINE_PASSED', "Muddat o'tdi"), ('ORDER_COMPLETED', 'Ish tugatildi'), ('MESSAGE', 'Yangi xabar')], max_length=30),
        ),
    ]
